electrodes_to_export_roi_categories: ~
electrodes_to_export_roi_name: none
analysis_settings:
  '1':
    label: Astart
    event: AudStart
    time:
    - 0
    - 0.55
    frequency:
    - 70
    - 150
  '2':
    label: Vstart
    event: Trial Onset
    time:
    - 0
    - 0.55
    frequency:
    - 70
    - 150
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
custom_roi_variable: none
custom_roi_type: Filter only
enable_custom_ROI: no
condition_variable: Condition
enable_second_condition_groupings: no
second_condition_groupings:
  '1':
    label: ML
    conditions: []
  '2':
    label: VL
    conditions: []
first_condition_groupings:
  '1':
    label: Ac
    conditions:
    - Ac
  '2':
    label: Vo
    conditions:
    - V
analysis_electrodes: '91-92 '
baseline_settings:
  window:
  - - -0.5
    - 0.0
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
reference_name: bipolar
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
epoch_choice: 5modalities
loaded_electrodes: 75-106
subject_code: YEU
project_name: mTurkWords
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
trial_outliers_list: ~
electrode_export_file_type: HDF5
frequencies_to_export: Collapsed, Analysis window(s) only
times_to_export: Raw, All available times
trials_to_export: Raw, Only trials used in grouping factors
electrodes_to_export: ''
electrode_export_data_type: tensor
