electrodes_to_export_roi_categories: ~
electrodes_to_export_roi_name: none
analysis_settings:
  '1':
    label: AudOnset
    event: AudStart
    time:
    - 0
    - 0.55
    frequency:
    - 70
    - 152
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
custom_roi_variable: none
custom_roi_type: Filter only
enable_custom_ROI: no
condition_variable: Condition
enable_second_condition_groupings: no
second_condition_groupings:
  '1':
    label: Ac
    conditions:
    - Ac_UNK
    - Ac_(0.8,0.9]
    - Ac_(0.9,1]
  '2':
    label: AV
    conditions:
    - AcV_UNK
    - AcV_(0.9,1]
    - AcV_(0.8,0.9]
first_condition_groupings:
  '1':
    label: Acc_UNK
    conditions:
    - AcV_UNK
  '2':
    label: Acc_81
    conditions:
    - AcV_(0.9,1]
    - AcV_(0.8,0.9]
  '3':
    label: Acc_47
    conditions:
    - AcV_(0.4,0.5]
    - AcV_(0.5,0.6]
    - AcV_(0.6,0.7]
analysis_electrodes: 33-35,39-49,85-90,92,94-104,170-174,177-178
baseline_settings:
  window:
  - - -0.5
    - 0.0
  scope: Per frequency, trial, and electrode
  unit_of_analysis: z-score Amplitude
reference_name: bipolar
epoch_choice__trial_ends: 3
epoch_choice__trial_starts: -1
epoch_choice: YEU_with_acc_Feb16
loaded_electrodes: 33-51,85-106,170-181
subject_code: YEU
project_name: mTurkWords
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
trial_outliers_list: ~
electrode_export_file_type: HDF5
frequencies_to_export: Collapsed, Analysis window(s) only
times_to_export: Raw, All available times
trials_to_export: Raw, Only trials used in grouping factors
electrodes_to_export: ''
electrode_export_data_type: tensor
