electrode_export_data_type: tensor
electrodes_to_export: ''
trials_to_export: Raw, Only trials used in grouping factors
times_to_export: Raw, All available times
frequencies_to_export: Collapsed, Analysis window(s) only
electrode_export_file_type: HDF5
trial_outliers_list: ~
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
project_name: congruency
subject_code: YAF
loaded_electrodes: 41-42,47,52-55
epoch_choice: YAF_aayushi
epoch_choice__trial_starts: -1.0
epoch_choice__trial_ends: 2.0
reference_name: yafcar
baseline_settings:
  window:
  - - -0.5
    - 0.0
  scope: Per frequency, trial, and electrode
  unit_of_analysis: z-score Amplitude
analysis_electrodes: 41-42,47,52-55
first_condition_groupings:
  '1':
    label: AV
    conditions:
    - last_av
    - drive_av
    - known_av
    - meant_av
  '2':
    label: Vo
    conditions:
    - last_v
    - drive_v
    - known_v
    - meant_v
  '3':
    label: Ac
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
second_condition_groupings:
  '1':
    label: ML
    conditions: []
  '2':
    label: VL
    conditions: []
enable_second_condition_groupings: no
condition_variable: Condition
enable_custom_ROI: no
custom_roi_type: Filter only
custom_roi_variable: none
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
analysis_settings:
  '1':
    label: AudStart
    event: AuditoryStart
    time:
    - 0
    - 0.6
    frequency:
    - 70
    - 150
  '2':
    label: VisStart
    event: VisualStart
    time:
    - 0.0
    - 0.8
    frequency:
    - 70
    - 150
electrodes_to_export_roi_name: none
electrodes_to_export_roi_categories: ~
