electrode_export_data_type: tensor
electrodes_to_export: ''
trials_to_export: Raw, Only trials used in grouping factors
times_to_export: Raw, All available times
frequencies_to_export: Collapsed, Analysis window(s) only
electrode_export_file_type: HDF5
trial_outliers_list: ~
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
project_name: mTurkWords
subject_code: YEU
loaded_electrodes: 33-34
epoch_choice: Acc_UTO_YEU_intelligibility_ALL_voao
epoch_choice__trial_starts: -1
epoch_choice__trial_ends: 3
reference_name: bipolar
baseline_settings:
  window:
  - - -0.5
    - 0.0
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
analysis_electrodes: '34'
first_condition_groupings:
  '1':
    label: Ac
    conditions:
    - Ac_c0_2
    - Ac_c2_4
    - Ac_c4_6
    - Ac_c6_8
    - Ac_c8_1
  '2':
    label: Vo
    conditions:
    - Vo
second_condition_groupings:
  '1':
    label: LowIntell
    conditions: []
  '2':
    label: HighIntell
    conditions: []
enable_second_condition_groupings: no
condition_variable: Condition
enable_custom_ROI: no
custom_roi_type: Filter only
custom_roi_variable: none
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
analysis_settings:
  '1':
    label: AS
    event: AudStart
    time:
    - 0
    - 0.6
    frequency:
    - 70
    - 150
electrodes_to_export_roi_name: none
electrodes_to_export_roi_categories: ~
