electrode_export_data_type: tensor
electrodes_to_export: ''
trials_to_export: Raw, Only trials used in grouping factors
times_to_export: Raw, All available times
frequencies_to_export: Collapsed, Analysis window(s) only
electrode_export_file_type: HDF5
trial_outliers_list: '270'
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
project_name: demo
subject_code: DemoSubject
loaded_electrodes: 13-16,24
epoch_choice: auditory_onset
epoch_choice__trial_starts: -0.55
epoch_choice__trial_ends: 3
reference_name: default
baseline_settings:
  window:
  - - -0.5
    - 0.0
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
analysis_electrodes: '13 '
first_condition_groupings:
  '1':
    label: All Conditions
    conditions:
    - drive_a
    - drive_av
    - drive_v
    - known_a
    - known_av
    - known_v
    - last_a
    - last_av
    - last_v
    - meant_a
    - meant_av
    - meant_v
    - press_AV
  '2':
    label: AV-inc
    conditions:
    - AdriveVlast
    - AknownVmeant
    - AlastVknown
second_condition_groupings:
  '1':
    label: ML
    conditions: []
  '2':
    label: VL
    conditions: []
enable_second_condition_groupings: no
condition_variable: Condition
enable_custom_ROI: no
custom_roi_type: Filter only
custom_roi_variable: none
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
analysis_settings:
  '1':
    label: VisStart
    event: Trial Onset
    time:
    - 0
    - 0.8
    frequency:
    - 70
    - 150
electrodes_to_export_roi_name: none
electrodes_to_export_roi_categories: ~
